### PR TITLE
Added FreeType 2.6-alldeps

### PR DESCRIPTION
**Pull request by brisingraerowing**
I added FreeType 2.6 with all dependencies.

### CODE REVIEW

**Comment by Robmaister** [comment]
Looks good, thanks! :+1:

Fixes #2

**Comment by brisingraerowing** [comment]
I saw you renamed the folders. I will try to name them in the manner you use to be consistent next time. I didn't see how you named them.

**Comment by Robmaister** [comment]
No worries, didn't even realize they were different until after I went through and built 2.6 without extra dependencies. :smile:

**Comment by brisingraerowing** [comment]
Just a side note, if any new versions of freetype or its dependencies come out within the next three to four weeks, I won't be able to build them as my laptop failed. The motherboard (and everything else other than the hard drive) fried due to a faulty power supply circuit that Sony apparently knew about but didn't do anything about. The hard drive escaped as there was a surge protector circuit between it and the motherboard.

I have my dad's old Asus, but it is slow and has only 3 GB RAM, most of which is used by the system.

**Comment by brisingraerowing** [comment]
I should be able to get a new one next month.

**Comment by brisingraerowing** [comment]
Weird. That came out as two posts. :confused:

**Comment by Robmaister** [comment]
That sucks :(

Looking at the release history, though, I doubt you have much to worry about though

**Pull request merged**
